### ISSUE TITLE
Heartbeat check needs improving.

### ISSUE THREAD

**Issue by WilsontheWolf** [Testausserveri/testaustime-vscode#6]
Right now the heartbeat check just checks if the window is focused.

https://github.com/Testaustime/testaustime-vscode/blob/795a0cd5225fb03f1d3463a1f29ae4c29332de15/src/testaustime.ts#L139-L142

This means if vscode is left open and focused, you get this ![e](https://cdn.discordapp.com/attachments/519997113652871181/1027454513952595998/unknown.png)

**Comment by DrVilepis** [comment]
I find this extremely funny, but it still needs to be fixed.

There has been some work on this, namely by @J3RQ, here is a working implementation in javascript:

https://github.com/J3RQ/testaustime-vscode-js/blob/99b0ddc746547453e9b23ee119bdf0dd6a21ca17/src/testaustime.js#L62-L74

The code in question:
```js
    async TestaustimeActivate() {
        if (vscode.window.activeTextEditor != undefined) this.heartbeat()
        this.timer = setInterval(() => {
            if (vscode.window.activeTextEditor != undefined) {
                const pointerpos = vscode.window.activeTextEditor.selection.active
                const pointerArray = [pointerpos['_line'], pointerpos['_character']]
                if (this.pointer[0] != pointerArray[0] || this.pointer[1] != pointerArray[1]) {
                    this.pointer = pointerArray
                    this.heartbeat()
                }
            }
        }, 30000);
    }
```

If anyone is interested in implementing this in typescript and making a pull request to this repository, feel free.

**Comment by DrVilepis** [comment]
The fact that you can have 2d coding time in one day is a different problem in itself, that should be fixed in the frontend, or in the backend by adding a new endpoint.
